<?php

declare(strict_types=1);

namespace Webgriffe\SyliusKlarnaPaymentsPlugin\Client\Enum;

enum OrganizationEntityType: string
{
    case LIMITED_COMPANY = 'LIMITED_COMPANY';
    case PUBLIC_LIMITED_COMPANY = 'PUBLIC_LIMITED_COMPANY';
    case ENTREPRENEURIAL_COMPANY = 'ENTREPRENEURIAL_COMPANY';
    case LIMITED_PARTNERSHIP_LIMITED_COMPANY = 'LIMITED_PARTNERSHIP_LIMITED_COMPANY';
    case LIMITED_PARTNERSHIP = 'LIMITED_PARTNERSHIP';
    case GENERAL_PARTNERSHIP = 'GENERAL_PARTNERSHIP';
    case REGISTERED_SOLE_TRADER = 'REGISTERED_SOLE_TRADER';
    case SOLE_TRADER = 'SOLE_TRADER';
    case CIVIL_LAW_PARTNERSHIP = 'CIVIL_LAW_PARTNERSHIP';
    case PUBLIC_INSTITUTION = 'PUBLIC_INSTITUTION';
    case OTHER = 'OTHER';
}
