services:
    sylius-app:
        profiles: [ "disabled" ]

    sylius-mysql:
        ports:
            - 13306:3306

    mailpit:
        image: axllent/mailpit
        ports:
            - "18025:8025"
            - "11025:1025"
