# Delete these routes and define your own shop routes here

webgriffe_sylius_klarna_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Webgriffe\SyliusKlarnaPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

webgriffe_sylius_klarna_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Webgriffe\SyliusKlarnaPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
